sudo: required

language: ruby

rvm:
  - ruby 2.2.3

services:
  - docker

before_install:
  - docker-compose up --build -d

after_script:
  - docker-compose down

script: 
  - bundle exec rails test

