version: '2' 
services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/dockerizing-rails5
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '3000:3000' 
    depends_on:
      - db
  db:
    build: ./postgresql/    
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=docker_development
  web:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - app
    ports: 
      - '80:80'
    volumes:
      - ./nginx.template:/etc/nginx/conf.d/app.template
    environment:
      - NGINX_HOST=127.1.0.0
      - NGINX_PORT=80  
    command: /bin/bash -c "envsubst '$${NGINX_PORT} $${NGINX_HOST}' < /etc/nginx/conf.d/app.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
